from backend.metadata.types import (
    CommentSource,
    IsoLang,
    ParshaInfo,
    TanakhBookInfo,
    TanakhSectionMetadata,
    TextSource,
)

MRK_SOURCE = "mosad-harav-cook"
JPS_GSE_SOURCE = "JPS-gender-sensitive"
RASHI_METSUDAH = "neviim-rashi-metsudah"


NEVIIM_METADATA = TanakhSectionMetadata(
    title={MRK_SOURCE: "Пророки", JPS_GSE_SOURCE: "Prophets"},
    subtitle=None,
    text_sources=[
        TextSource(
            key=MRK_SOURCE,
            mark="[МРК]",
            description="Текст в переводе издательства Мосад hаРав Кук, под руководством р. Давида Йосифона",
            links=[
                r"https://toraonline.ru/index.htm",
                r"http://holyscripture.ru/bible/?t=josiphon",
            ],
            language=IsoLang.RU,
        ),
        TextSource(
            key=JPS_GSE_SOURCE,
            mark="[RJPS]",
            description=(
                "The JPS Tanakh: Gender-Sensitive Edition издательства "
                + "The Jewish Publication Society под редакцией р. Давида Е. С. Штейна"
            ),
            links=[
                r"https://jps.org/books/the-jps-tanakh-gender-sensitive-edition/",
                r"https://jps.org/wp-content/uploads/2023/05/JPS-TANAKH-Gender-Sensitive-Preface.pdf",
                r"https://jps.org/wp-content/uploads/2023/05/JPS-Gender-Sensitive-Tanakh-Notes-on-Gender.pdf",
            ],
            language=IsoLang.EN,
        ),
    ],
    comment_sources=[
        CommentSource(
            key=RASHI_METSUDAH,
            name="Раши [Metshudah]",
            links=[
                r"https://judaicaplaza.com/products/ibs-m119",
            ],
            language=IsoLang.EN,
        )
    ],
    books=[
        TanakhBookInfo(id=6, name={MRK_SOURCE: "Йеhошуа", JPS_GSE_SOURCE: "Joshua"}),
        TanakhBookInfo(id=7, name={MRK_SOURCE: "Шойфтим", JPS_GSE_SOURCE: "Judges"}),
        TanakhBookInfo(id=8, name={MRK_SOURCE: "Шемуэйл I", JPS_GSE_SOURCE: "I Samuel"}),
        TanakhBookInfo(id=9, name={MRK_SOURCE: "Шемуэйл II", JPS_GSE_SOURCE: "II Samuel"}),
        TanakhBookInfo(id=10, name={MRK_SOURCE: "Мелахим I", JPS_GSE_SOURCE: "I Kings"}),
        TanakhBookInfo(id=11, name={MRK_SOURCE: "Мелахим II", JPS_GSE_SOURCE: "II Kings"}),
        TanakhBookInfo(id=12, name={MRK_SOURCE: "Йирмейа", JPS_GSE_SOURCE: "Jeremiah"}),
        TanakhBookInfo(id=13, name={MRK_SOURCE: "Йехэзкэйл", JPS_GSE_SOURCE: "Ezekiel"}),
        TanakhBookInfo(id=14, name={MRK_SOURCE: "Йешайа", JPS_GSE_SOURCE: "Isaiah"}),
        TanakhBookInfo(id=15, name={MRK_SOURCE: "Ошеа", JPS_GSE_SOURCE: "Hosea"}),
        TanakhBookInfo(id=16, name={MRK_SOURCE: "Йоель", JPS_GSE_SOURCE: "Joel"}),
        TanakhBookInfo(id=17, name={MRK_SOURCE: "Амос", JPS_GSE_SOURCE: "Amos"}),
        TanakhBookInfo(id=18, name={MRK_SOURCE: "Овадья", JPS_GSE_SOURCE: "Obadiah"}),
        TanakhBookInfo(id=19, name={MRK_SOURCE: "Йона", JPS_GSE_SOURCE: "Jonah"}),
        TanakhBookInfo(id=20, name={MRK_SOURCE: "Миха", JPS_GSE_SOURCE: "Micah"}),
        TanakhBookInfo(id=21, name={MRK_SOURCE: "Нахум", JPS_GSE_SOURCE: "Nahum"}),
        TanakhBookInfo(id=22, name={MRK_SOURCE: "Хавакук", JPS_GSE_SOURCE: "Habakkuk"}),
        TanakhBookInfo(id=23, name={MRK_SOURCE: "Цфанья", JPS_GSE_SOURCE: "Zephaniah"}),
        TanakhBookInfo(id=24, name={MRK_SOURCE: "Хагай", JPS_GSE_SOURCE: "Haggai"}),
        TanakhBookInfo(id=25, name={MRK_SOURCE: "Зехарья", JPS_GSE_SOURCE: "Zechariah"}),
        TanakhBookInfo(id=26, name={MRK_SOURCE: "Малахи", JPS_GSE_SOURCE: "Malachi"}),
    ],
    parshas=[
        ParshaInfo(
            id=55,
            book_id=6,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(11, 23),
            name={
                MRK_SOURCE: "Йеhошуа 1–11",
                JPS_GSE_SOURCE: "Joshua 1–11",
            },
            url_name="joshua-1-11",
        ),
        ParshaInfo(
            id=56,
            book_id=6,
            chapter_verse_start=(12, 1),
            chapter_verse_end=(19, 51),
            name={
                MRK_SOURCE: "Йеhошуа 12–19",
                JPS_GSE_SOURCE: "Joshua 12–19",
            },
            url_name="joshua-12-19",
        ),
        ParshaInfo(
            id=57,
            book_id=6,
            chapter_verse_start=(20, 1),
            chapter_verse_end=(24, 33),
            name={
                MRK_SOURCE: "Йеhошуа 20–24",
                JPS_GSE_SOURCE: "Joshua 20–24",
            },
            url_name="joshua-20-24",
        ),
        ParshaInfo(
            id=58,
            book_id=7,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(11, 40),
            name={
                MRK_SOURCE: "Шойфтим 1–11",
                JPS_GSE_SOURCE: "Judges 1–11",
            },
            url_name="judges-1-11",
        ),
        ParshaInfo(
            id=59,
            book_id=7,
            chapter_verse_start=(12, 1),
            chapter_verse_end=(21, 25),
            name={
                MRK_SOURCE: "Шойфтим 12–21",
                JPS_GSE_SOURCE: "Judges 12–21",
            },
            url_name="judges-12-21",
        ),
        ParshaInfo(
            id=60,
            book_id=8,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(8, 22),
            name={
                MRK_SOURCE: "Шемуэйл I 1–8",
                JPS_GSE_SOURCE: "I Samuel 1–8",
            },
            url_name="first-samuel-1-8",
        ),
        ParshaInfo(
            id=61,
            book_id=8,
            chapter_verse_start=(9, 1),
            chapter_verse_end=(13, 23),
            name={
                MRK_SOURCE: "Шемуэйл I 9–13",
                JPS_GSE_SOURCE: "I Samuel 9–13",
            },
            url_name="first-samuel-9-13",
        ),
        ParshaInfo(
            id=62,
            book_id=8,
            chapter_verse_start=(14, 1),
            chapter_verse_end=(25, 44),
            name={
                MRK_SOURCE: "Шемуэйл I 14–25",
                JPS_GSE_SOURCE: "I Samuel 14–25",
            },
            url_name="first-samuel-14-25",
        ),
        ParshaInfo(
            id=63,
            book_id=8,
            chapter_verse_start=(26, 1),
            chapter_verse_end=(31, 13),
            name={
                MRK_SOURCE: "Шемуэйл I 26–31",
                JPS_GSE_SOURCE: "I Samuel 26–31",
            },
            url_name="first-samuel-26-31",
            parsha_group_leader_id=63,
        ),
        ParshaInfo(
            id=64,
            book_id=9,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(7, 29),
            name={
                MRK_SOURCE: "Шемуэйл II 1–7",
                JPS_GSE_SOURCE: "II Samuel 1–7",
            },
            url_name="second-samuel-1-7",
            parsha_group_leader_id=63,
        ),
        ParshaInfo(
            id=65,
            book_id=9,
            chapter_verse_start=(8, 1),
            chapter_verse_end=(18, 32),
            name={
                MRK_SOURCE: "Шемуэйл II 8–18",
                JPS_GSE_SOURCE: "II Samuel 8–18",
            },
            url_name="second-samuel-8-18",
        ),
        ParshaInfo(
            id=66,
            book_id=9,
            chapter_verse_start=(19, 1),
            chapter_verse_end=(24, 25),
            name={
                MRK_SOURCE: "Шемуэйл II 19–24",
                JPS_GSE_SOURCE: "II Samuel 19–24",
            },
            url_name="second-samuel-19-24",
        ),
        ParshaInfo(
            id=67,
            book_id=10,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(6, 38),
            name={
                MRK_SOURCE: "Мелахим I 1–6",
                JPS_GSE_SOURCE: "I Kings 1–6",
            },
            url_name="first-kings-1-6",
        ),
        ParshaInfo(
            id=68,
            book_id=10,
            chapter_verse_start=(7, 1),
            chapter_verse_end=(10, 29),
            name={
                MRK_SOURCE: "Мелахим I 7–10",
                JPS_GSE_SOURCE: "I Kings 7–10",
            },
            url_name="first-kings-7-10",
        ),
        ParshaInfo(
            id=69,
            book_id=10,
            chapter_verse_start=(11, 1),
            chapter_verse_end=(19, 21),
            name={
                MRK_SOURCE: "Мелахим I 11–19",
                JPS_GSE_SOURCE: "I Kings 11–19",
            },
            url_name="first-kings-11-19",
        ),
        ParshaInfo(
            id=70,
            book_id=10,
            chapter_verse_start=(20, 1),
            chapter_verse_end=(22, 54),
            name={
                MRK_SOURCE: "Мелахим I 20–22",
                JPS_GSE_SOURCE: "I Kings 20–22",
            },
            url_name="first-kings-20-22",
            parsha_group_leader_id=70,
        ),
        ParshaInfo(
            id=71,
            book_id=11,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(5, 27),
            name={
                MRK_SOURCE: "Мелахим II 1–5",
                JPS_GSE_SOURCE: "II Kings 1–5",
            },
            url_name="second-kings-1-5",
            parsha_group_leader_id=70,
        ),
        ParshaInfo(
            id=72,
            book_id=11,
            chapter_verse_start=(6, 1),
            chapter_verse_end=(12, 22),
            name={
                MRK_SOURCE: "Мелахим II 6–12",
                JPS_GSE_SOURCE: "II Kings 6–12",
            },
            url_name="second-kings-6-12",
        ),
        ParshaInfo(
            id=73,
            book_id=11,
            chapter_verse_start=(13, 1),
            chapter_verse_end=(18, 37),
            name={
                MRK_SOURCE: "Мелахим II 13–18",
                JPS_GSE_SOURCE: "II Kings 13–18",
            },
            url_name="second-kings-13-18",
        ),
        ParshaInfo(
            id=74,
            book_id=11,
            chapter_verse_start=(19, 1),
            chapter_verse_end=(25, 30),
            name={
                MRK_SOURCE: "Мелахим II 19–25",
                JPS_GSE_SOURCE: "II Kings 19–25",
            },
            url_name="second-kings-19-25",
        ),
        ParshaInfo(
            id=75,
            book_id=12,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(8, 23),
            name={
                MRK_SOURCE: "Йирмейа 1–8",
                JPS_GSE_SOURCE: "Jeremiah 1–8",
            },
            url_name="jeremiah-1-8",
        ),
        ParshaInfo(
            id=76,
            book_id=12,
            chapter_verse_start=(9, 1),
            chapter_verse_end=(17, 27),
            name={
                MRK_SOURCE: "Йирмейа 9–17",
                JPS_GSE_SOURCE: "Jeremiah 9–17",
            },
            url_name="jeremiah-9-17",
        ),
        ParshaInfo(
            id=77,
            book_id=12,
            chapter_verse_start=(18, 1),
            chapter_verse_end=(31, 39),
            name={
                MRK_SOURCE: "Йирмейа 18–31",
                JPS_GSE_SOURCE: "Jeremiah 18–31",
            },
            url_name="jeremiah-18-31",
        ),
        ParshaInfo(
            id=78,
            book_id=12,
            chapter_verse_start=(32, 1),
            chapter_verse_end=(37, 21),
            name={
                MRK_SOURCE: "Йирмейа 32–37",
                JPS_GSE_SOURCE: "Jeremiah 32–37",
            },
            url_name="jeremiah-32-37",
        ),
        ParshaInfo(
            id=79,
            book_id=12,
            chapter_verse_start=(38, 1),
            chapter_verse_end=(48, 47),
            name={
                MRK_SOURCE: "Йирмейа 38–48",
                JPS_GSE_SOURCE: "Jeremiah 38–48",
            },
            url_name="jeremiah-38-48",
        ),
        ParshaInfo(
            id=80,
            book_id=12,
            chapter_verse_start=(49, 1),
            chapter_verse_end=(52, 34),
            name={
                MRK_SOURCE: "Йирмейа 49–52",
                JPS_GSE_SOURCE: "Jeremiah 49–52",
            },
            url_name="jeremiah-49-52",
        ),
        ParshaInfo(
            id=81,
            book_id=13,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(9, 11),
            name={
                MRK_SOURCE: "Йехэзкэйл 1–9",
                JPS_GSE_SOURCE: "Ezekiel 1–9",
            },
            url_name="ezekiel-1-9",
        ),
        ParshaInfo(
            id=82,
            book_id=13,
            chapter_verse_start=(10, 1),
            chapter_verse_end=(17, 24),
            name={
                MRK_SOURCE: "Йехэзкэйл 10–17",
                JPS_GSE_SOURCE: "Ezekiel 10–17",
            },
            url_name="ezekiel-10-17",
        ),
        ParshaInfo(
            id=83,
            book_id=13,
            chapter_verse_start=(18, 1),
            chapter_verse_end=(22, 31),
            name={
                MRK_SOURCE: "Йехэзкэйл 18–22",
                JPS_GSE_SOURCE: "Ezekiel 18–22",
            },
            url_name="ezekiel-18-22",
        ),
        ParshaInfo(
            id=84,
            book_id=13,
            chapter_verse_start=(23, 1),
            chapter_verse_end=(27, 36),
            name={
                MRK_SOURCE: "Йехэзкэйл 23–27",
                JPS_GSE_SOURCE: "Ezekiel 23–27",
            },
            url_name="ezekiel-23-27",
        ),
        ParshaInfo(
            id=85,
            book_id=13,
            chapter_verse_start=(28, 1),
            chapter_verse_end=(30, 26),
            name={
                MRK_SOURCE: "Йехэзкэйл 28–30",
                JPS_GSE_SOURCE: "Ezekiel 28–30",
            },
            url_name="ezekiel-28-30",
        ),
        ParshaInfo(
            id=86,
            book_id=13,
            chapter_verse_start=(31, 1),
            chapter_verse_end=(40, 49),
            name={
                MRK_SOURCE: "Йехэзкэйл 31–40",
                JPS_GSE_SOURCE: "Ezekiel 31–40",
            },
            url_name="ezekiel-31-40",
        ),
        ParshaInfo(
            id=87,
            book_id=13,
            chapter_verse_start=(41, 1),
            chapter_verse_end=(43, 27),
            name={
                MRK_SOURCE: "Йехэзкэйл 41–43",
                JPS_GSE_SOURCE: "Ezekiel 41–43",
            },
            url_name="ezekiel-41-43",
        ),
        ParshaInfo(
            id=88,
            book_id=13,
            chapter_verse_start=(44, 1),
            chapter_verse_end=(46, 24),
            name={
                MRK_SOURCE: "Йехэзкэйл 44–46",
                JPS_GSE_SOURCE: "Ezekiel 44–46",
            },
            url_name="ezekiel-44-46",
        ),
        ParshaInfo(
            id=89,
            book_id=13,
            chapter_verse_start=(47, 1),
            chapter_verse_end=(48, 35),
            name={
                MRK_SOURCE: "Йехэзкэйл 47–48",
                JPS_GSE_SOURCE: "Ezekiel 47–48",
            },
            url_name="ezekiel-47-48",
        ),
        ParshaInfo(
            id=90,
            book_id=14,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(5, 30),
            name={
                MRK_SOURCE: "Йешайа 1–5",
                JPS_GSE_SOURCE: "Isaiah 1–5",
            },
            url_name="firstsaiah-1-5",
        ),
        ParshaInfo(
            id=91,
            book_id=14,
            chapter_verse_start=(6, 1),
            chapter_verse_end=(9, 20),
            name={
                MRK_SOURCE: "Йешайа 6–9",
                JPS_GSE_SOURCE: "Isaiah 6–9",
            },
            url_name="firstsaiah-6-9",
        ),
        ParshaInfo(
            id=92,
            book_id=14,
            chapter_verse_start=(10, 1),
            chapter_verse_end=(13, 22),
            name={
                MRK_SOURCE: "Йешайа 10–13",
                JPS_GSE_SOURCE: "Isaiah 10–13",
            },
            url_name="firstsaiah-10-13",
        ),
        ParshaInfo(
            id=93,
            book_id=14,
            chapter_verse_start=(14, 1),
            chapter_verse_end=(20, 6),
            name={
                MRK_SOURCE: "Йешайа 14–20",
                JPS_GSE_SOURCE: "Isaiah 14–20",
            },
            url_name="firstsaiah-14-20",
        ),
        ParshaInfo(
            id=94,
            book_id=14,
            chapter_verse_start=(21, 1),
            chapter_verse_end=(24, 23),
            name={
                MRK_SOURCE: "Йешайа 21–24",
                JPS_GSE_SOURCE: "Isaiah 21–24",
            },
            url_name="firstsaiah-21-24",
        ),
        ParshaInfo(
            id=95,
            book_id=14,
            chapter_verse_start=(25, 1),
            chapter_verse_end=(29, 24),
            name={
                MRK_SOURCE: "Йешайа 25–29",
                JPS_GSE_SOURCE: "Isaiah 25–29",
            },
            url_name="firstsaiah-25-29",
        ),
        ParshaInfo(
            id=96,
            book_id=14,
            chapter_verse_start=(30, 1),
            chapter_verse_end=(33, 24),
            name={
                MRK_SOURCE: "Йешайа 30–33",
                JPS_GSE_SOURCE: "Isaiah 30–33",
            },
            url_name="firstsaiah-30-33",
        ),
        ParshaInfo(
            id=97,
            book_id=14,
            chapter_verse_start=(34, 1),
            chapter_verse_end=(40, 31),
            name={
                MRK_SOURCE: "Йешайа 34–40",
                JPS_GSE_SOURCE: "Isaiah 34–40",
            },
            url_name="firstsaiah-34-40",
        ),
        ParshaInfo(
            id=98,
            book_id=14,
            chapter_verse_start=(41, 1),
            chapter_verse_end=(44, 28),
            name={
                MRK_SOURCE: "Йешайа 41–44",
                JPS_GSE_SOURCE: "Isaiah 41–44",
            },
            url_name="firstsaiah-41-44",
        ),
        ParshaInfo(
            id=99,
            book_id=14,
            chapter_verse_start=(45, 1),
            chapter_verse_end=(49, 26),
            name={
                MRK_SOURCE: "Йешайа 45–49",
                JPS_GSE_SOURCE: "Isaiah 45–49",
            },
            url_name="firstsaiah-45-49",
        ),
        ParshaInfo(
            id=100,
            book_id=14,
            chapter_verse_start=(50, 1),
            chapter_verse_end=(58, 14),
            name={
                MRK_SOURCE: "Йешайа 50–58",
                JPS_GSE_SOURCE: "Isaiah 50–58",
            },
            url_name="firstsaiah-50-58",
        ),
        ParshaInfo(
            id=101,
            book_id=14,
            chapter_verse_start=(59, 1),
            chapter_verse_end=(66, 24),
            name={
                MRK_SOURCE: "Йешайа 59–66",
                JPS_GSE_SOURCE: "Isaiah 59–66",
            },
            url_name="firstsaiah-59-66",
        ),
        ParshaInfo(
            id=102,
            book_id=15,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(6, 11),
            name={
                MRK_SOURCE: "Ошеа 1–6",
                JPS_GSE_SOURCE: "Hosea 1–6",
            },
            url_name="hosea-1-6",
        ),
        ParshaInfo(
            id=103,
            book_id=15,
            chapter_verse_start=(7, 1),
            chapter_verse_end=(12, 15),
            name={
                MRK_SOURCE: "Ошеа 7–12",
                JPS_GSE_SOURCE: "Hosea 7–12",
            },
            url_name="hosea-7-12",
        ),
        ParshaInfo(
            id=104,
            book_id=15,
            chapter_verse_start=(13, 1),
            chapter_verse_end=(14, 10),
            name={
                MRK_SOURCE: "Ошеа 13–14",
                JPS_GSE_SOURCE: "Hosea 13–14",
            },
            url_name="hosea-13-14",
        ),
        ParshaInfo(
            id=105,
            book_id=16,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(4, 21),
            name={
                MRK_SOURCE: "Йоель",
                JPS_GSE_SOURCE: "Joel",
            },
            url_name="joel",
            parsha_group_leader_id=105,
        ),
        ParshaInfo(
            id=106,
            book_id=17,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(9, 15),
            name={
                MRK_SOURCE: "Амос",
                JPS_GSE_SOURCE: "Amos",
            },
            url_name="amos",
            parsha_group_leader_id=105,
        ),
        ParshaInfo(
            id=107,
            book_id=18,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(1, 21),
            name={
                MRK_SOURCE: "Овадья",
                JPS_GSE_SOURCE: "Obadiah",
            },
            url_name="obadiah",
            parsha_group_leader_id=107,
        ),
        ParshaInfo(
            id=108,
            book_id=19,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(4, 11),
            name={
                MRK_SOURCE: "Йона",
                JPS_GSE_SOURCE: "Jonah",
            },
            url_name="jonah",
            parsha_group_leader_id=107,
        ),
        ParshaInfo(
            id=109,
            book_id=20,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(7, 20),
            name={
                MRK_SOURCE: "Миха",
                JPS_GSE_SOURCE: "Micah",
            },
            url_name="micah",
            parsha_group_leader_id=107,
        ),
        ParshaInfo(
            id=110,
            book_id=21,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 19),
            name={
                MRK_SOURCE: "Нахум",
                JPS_GSE_SOURCE: "Nahum",
            },
            url_name="nahum",
            parsha_group_leader_id=110,
        ),
        ParshaInfo(
            id=111,
            book_id=22,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 19),
            name={
                MRK_SOURCE: "Хавакук",
                JPS_GSE_SOURCE: "Habakkuk",
            },
            url_name="habakkuk",
            parsha_group_leader_id=110,
        ),
        ParshaInfo(
            id=112,
            book_id=23,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 20),
            name={
                MRK_SOURCE: "Цфанья",
                JPS_GSE_SOURCE: "Zephaniah",
            },
            url_name="zephaniah",
            parsha_group_leader_id=110,
        ),
        ParshaInfo(
            id=113,
            book_id=24,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(2, 23),
            name={
                MRK_SOURCE: "Хагай",
                JPS_GSE_SOURCE: "Haggai",
            },
            url_name="haggai",
            parsha_group_leader_id=110,
        ),
        ParshaInfo(
            id=114,
            book_id=25,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(11, 17),
            name={
                MRK_SOURCE: "Зехарья 1–11",
                JPS_GSE_SOURCE: "Zechariah 1–11",
            },
            url_name="zechariah-1-11",
        ),
        ParshaInfo(
            id=115,
            book_id=25,
            chapter_verse_start=(12, 1),
            chapter_verse_end=(14, 21),
            name={
                MRK_SOURCE: "Зехарья 12–14",
                JPS_GSE_SOURCE: "Zechariah 12–14",
            },
            url_name="zechariah-12-14",
        ),
        ParshaInfo(
            id=116,
            book_id=26,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 24),
            name={
                MRK_SOURCE: "Малахи",
                JPS_GSE_SOURCE: "Malachi",
            },
            url_name="malachi",
        ),
    ],
)
