from backend.metadata.types import (
    IsoLang,
    ParshaInfo,
    TanakhBookInfo,
    TanakhSectionMetadata,
    TextSource,
)

MRK_SOURCE = "mosad-harav-cook"


NEVIIM_METADATA = TanakhSectionMetadata(
    title={
        MRK_SOURCE: "Пророки",
    },
    subtitle=None,
    text_sources=[
        TextSource(
            key=MRK_SOURCE,
            mark="[МРК]",
            description="Текст в переводе издательства Мосад hаРав Кук, под руководством р. Давида Йосифона",
            links=[
                r"https://toraonline.ru/index.htm",
                r"http://holyscripture.ru/bible/?t=josiphon",
            ],
            language=IsoLang.RU,
        )
    ],
    comment_sources=[],
    books=[
        TanakhBookInfo(id=6, name={MRK_SOURCE: "Йеhошуа"}),
        TanakhBookInfo(id=7, name={MRK_SOURCE: "Шойфтим"}),
        TanakhBookInfo(id=8, name={MRK_SOURCE: "Шемуэйл I"}),
        TanakhBookInfo(id=9, name={MRK_SOURCE: "Шемуэйл II"}),
        TanakhBookInfo(id=10, name={MRK_SOURCE: "Мелахим I"}),
        TanakhBookInfo(id=11, name={MRK_SOURCE: "Мелахим II"}),
        TanakhBookInfo(id=12, name={MRK_SOURCE: "Йирмейа"}),
        TanakhBookInfo(id=13, name={MRK_SOURCE: "Йехэзкэйл"}),
        TanakhBookInfo(id=14, name={MRK_SOURCE: "Йешайа"}),
        TanakhBookInfo(id=15, name={MRK_SOURCE: "Ошеа"}),
        TanakhBookInfo(id=16, name={MRK_SOURCE: "Йоель"}),
        TanakhBookInfo(id=17, name={MRK_SOURCE: "Амос"}),
        TanakhBookInfo(id=18, name={MRK_SOURCE: "Овадья"}),
        TanakhBookInfo(id=19, name={MRK_SOURCE: "Йона"}),
        TanakhBookInfo(id=20, name={MRK_SOURCE: "Миха"}),
        TanakhBookInfo(id=21, name={MRK_SOURCE: "Нахум"}),
        TanakhBookInfo(id=22, name={MRK_SOURCE: "Хавакук"}),
        TanakhBookInfo(id=23, name={MRK_SOURCE: "Цфанья"}),
        TanakhBookInfo(id=24, name={MRK_SOURCE: "Хагай"}),
        TanakhBookInfo(id=25, name={MRK_SOURCE: "Зехарья"}),
        TanakhBookInfo(id=26, name={MRK_SOURCE: "Малахи"}),
    ],
    parshas=[
        ParshaInfo(
            id=55,
            book_id=6,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(11, 23),
            name={MRK_SOURCE: "Йеhошуа 1–11"},
            url_name="joshua-1-11",
        ),
        ParshaInfo(
            id=56,
            book_id=6,
            chapter_verse_start=(12, 1),
            chapter_verse_end=(19, 51),
            name={MRK_SOURCE: "Йеhошуа 12–19"},
            url_name="joshua-12-19",
        ),
        ParshaInfo(
            id=57,
            book_id=6,
            chapter_verse_start=(20, 1),
            chapter_verse_end=(24, 33),
            name={MRK_SOURCE: "Йеhошуа 20–24"},
            url_name="joshua-20-24",
        ),
        ParshaInfo(
            id=58,
            book_id=7,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(11, 40),
            name={MRK_SOURCE: "Шойфтим 1–11"},
            url_name="judges-1-11",
        ),
        ParshaInfo(
            id=59,
            book_id=7,
            chapter_verse_start=(12, 1),
            chapter_verse_end=(21, 25),
            name={MRK_SOURCE: "Шойфтим 12–21"},
            url_name="judges-12-21",
        ),
        ParshaInfo(
            id=60,
            book_id=8,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(8, 22),
            name={MRK_SOURCE: "Шемуэйл I 1–8"},
            url_name="first-samuel-1-8",
        ),
        ParshaInfo(
            id=61,
            book_id=8,
            chapter_verse_start=(9, 1),
            chapter_verse_end=(13, 23),
            name={MRK_SOURCE: "Шемуэйл I 9–13"},
            url_name="first-samuel-9-13",
        ),
        ParshaInfo(
            id=62,
            book_id=8,
            chapter_verse_start=(14, 1),
            chapter_verse_end=(25, 44),
            name={MRK_SOURCE: "Шемуэйл I 14–25"},
            url_name="first-samuel-14-25",
        ),
        ParshaInfo(
            id=63,
            book_id=8,
            chapter_verse_start=(26, 1),
            chapter_verse_end=(31, 13),
            name={MRK_SOURCE: "Шемуэйл I 26–31"},
            url_name="first-samuel-26-31",
        ),
        ParshaInfo(
            id=64,
            book_id=9,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(7, 29),
            name={MRK_SOURCE: "Шемуэйл II 1–7"},
            url_name="second-samuel-1-7",
        ),
        ParshaInfo(
            id=65,
            book_id=9,
            chapter_verse_start=(8, 1),
            chapter_verse_end=(18, 32),
            name={MRK_SOURCE: "Шемуэйл II 8–18"},
            url_name="second-samuel-8-18",
        ),
        ParshaInfo(
            id=66,
            book_id=9,
            chapter_verse_start=(19, 1),
            chapter_verse_end=(24, 25),
            name={MRK_SOURCE: "Шемуэйл II 19–24"},
            url_name="second-samuel-19-24",
        ),
        ParshaInfo(
            id=67,
            book_id=10,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(6, 38),
            name={MRK_SOURCE: "Мелахим I 1–6"},
            url_name="first-kings-1-6",
        ),
        ParshaInfo(
            id=68,
            book_id=10,
            chapter_verse_start=(7, 1),
            chapter_verse_end=(10, 29),
            name={MRK_SOURCE: "Мелахим I 7–10"},
            url_name="first-kings-7-10",
        ),
        ParshaInfo(
            id=69,
            book_id=10,
            chapter_verse_start=(11, 1),
            chapter_verse_end=(19, 21),
            name={MRK_SOURCE: "Мелахим I 11–19"},
            url_name="first-kings-11-19",
        ),
        ParshaInfo(
            id=70,
            book_id=10,
            chapter_verse_start=(20, 1),
            chapter_verse_end=(22, 54),
            name={MRK_SOURCE: "Мелахим I 20–22"},
            url_name="first-kings-20-22",
        ),
        ParshaInfo(
            id=71,
            book_id=11,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(5, 27),
            name={MRK_SOURCE: "Мелахим II 1–5"},
            url_name="second-kings-1-5",
        ),
        ParshaInfo(
            id=72,
            book_id=11,
            chapter_verse_start=(6, 1),
            chapter_verse_end=(12, 22),
            name={MRK_SOURCE: "Мелахим II 6–12"},
            url_name="second-kings-6-12",
        ),
        ParshaInfo(
            id=73,
            book_id=11,
            chapter_verse_start=(13, 1),
            chapter_verse_end=(18, 37),
            name={MRK_SOURCE: "Мелахим II 13–18"},
            url_name="second-kings-13-18",
        ),
        ParshaInfo(
            id=74,
            book_id=11,
            chapter_verse_start=(19, 1),
            chapter_verse_end=(25, 30),
            name={MRK_SOURCE: "Мелахим II 19–25"},
            url_name="second-kings-19-25",
        ),
        # FIXME
        ParshaInfo(
            id=75,
            book_id=12,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(8, 0),
            name={MRK_SOURCE: "Йирмейа 1–8"},
            url_name="jeremiah-1-8",
        ),
        ParshaInfo(
            id=76,
            book_id=12,
            chapter_verse_start=(9, 1),
            chapter_verse_end=(17, 0),
            name={MRK_SOURCE: "Йирмейа 9–17"},
            url_name="jeremiah-9-17",
        ),
        ParshaInfo(
            id=77,
            book_id=12,
            chapter_verse_start=(18, 1),
            chapter_verse_end=(31, 0),
            name={MRK_SOURCE: "Йирмейа 18–31"},
            url_name="jeremiah-18-31",
        ),
        ParshaInfo(
            id=78,
            book_id=12,
            chapter_verse_start=(32, 1),
            chapter_verse_end=(37, 0),
            name={MRK_SOURCE: "Йирмейа 32–37"},
            url_name="jeremiah-32-37",
        ),
        ParshaInfo(
            id=79,
            book_id=12,
            chapter_verse_start=(38, 1),
            chapter_verse_end=(48, 0),
            name={MRK_SOURCE: "Йирмейа 38–48"},
            url_name="jeremiah-38-48",
        ),
        ParshaInfo(
            id=80,
            book_id=12,
            chapter_verse_start=(49, 1),
            chapter_verse_end=(52, 0),
            name={MRK_SOURCE: "Йирмейа 49–52"},
            url_name="jeremiah-49-52",
        ),
        ParshaInfo(
            id=81,
            book_id=13,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(9, 0),
            name={MRK_SOURCE: "Йехэзкэйл 1–9"},
            url_name="ezekiel-1-9",
        ),
        ParshaInfo(
            id=82,
            book_id=13,
            chapter_verse_start=(10, 1),
            chapter_verse_end=(17, 0),
            name={MRK_SOURCE: "Йехэзкэйл 10–17"},
            url_name="ezekiel-10-17",
        ),
        ParshaInfo(
            id=83,
            book_id=13,
            chapter_verse_start=(18, 1),
            chapter_verse_end=(22, 0),
            name={MRK_SOURCE: "Йехэзкэйл 18–22"},
            url_name="ezekiel-18-22",
        ),
        ParshaInfo(
            id=84,
            book_id=13,
            chapter_verse_start=(23, 1),
            chapter_verse_end=(27, 0),
            name={MRK_SOURCE: "Йехэзкэйл 23–27"},
            url_name="ezekiel-23-27",
        ),
        ParshaInfo(
            id=85,
            book_id=13,
            chapter_verse_start=(28, 1),
            chapter_verse_end=(30, 0),
            name={MRK_SOURCE: "Йехэзкэйл 28–30"},
            url_name="ezekiel-28-30",
        ),
        ParshaInfo(
            id=86,
            book_id=13,
            chapter_verse_start=(31, 1),
            chapter_verse_end=(40, 0),
            name={MRK_SOURCE: "Йехэзкэйл 31–40"},
            url_name="ezekiel-31-40",
        ),
        ParshaInfo(
            id=87,
            book_id=13,
            chapter_verse_start=(41, 1),
            chapter_verse_end=(43, 0),
            name={MRK_SOURCE: "Йехэзкэйл 41–43"},
            url_name="ezekiel-41-43",
        ),
        ParshaInfo(
            id=88,
            book_id=13,
            chapter_verse_start=(44, 1),
            chapter_verse_end=(46, 0),
            name={MRK_SOURCE: "Йехэзкэйл 44–46"},
            url_name="ezekiel-44-46",
        ),
        ParshaInfo(
            id=89,
            book_id=13,
            chapter_verse_start=(47, 1),
            chapter_verse_end=(48, 0),
            name={MRK_SOURCE: "Йехэзкэйл 47–48"},
            url_name="ezekiel-47-48",
        ),
        ParshaInfo(
            id=90,
            book_id=14,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(5, 0),
            name={MRK_SOURCE: "Йешайа 1–5"},
            url_name="firstsaiah-1-5",
        ),
        ParshaInfo(
            id=91,
            book_id=14,
            chapter_verse_start=(6, 1),
            chapter_verse_end=(9, 0),
            name={MRK_SOURCE: "Йешайа 6–9"},
            url_name="firstsaiah-6-9",
        ),
        ParshaInfo(
            id=92,
            book_id=14,
            chapter_verse_start=(10, 1),
            chapter_verse_end=(13, 0),
            name={MRK_SOURCE: "Йешайа 10–13"},
            url_name="firstsaiah-10-13",
        ),
        ParshaInfo(
            id=93,
            book_id=14,
            chapter_verse_start=(14, 1),
            chapter_verse_end=(20, 0),
            name={MRK_SOURCE: "Йешайа 14–20"},
            url_name="firstsaiah-14-20",
        ),
        ParshaInfo(
            id=94,
            book_id=14,
            chapter_verse_start=(21, 1),
            chapter_verse_end=(24, 0),
            name={MRK_SOURCE: "Йешайа 21–24"},
            url_name="firstsaiah-21-24",
        ),
        ParshaInfo(
            id=95,
            book_id=14,
            chapter_verse_start=(25, 1),
            chapter_verse_end=(29, 0),
            name={MRK_SOURCE: "Йешайа 25–29"},
            url_name="firstsaiah-25-29",
        ),
        ParshaInfo(
            id=96,
            book_id=14,
            chapter_verse_start=(30, 1),
            chapter_verse_end=(33, 0),
            name={MRK_SOURCE: "Йешайа 30–33"},
            url_name="firstsaiah-30-33",
        ),
        ParshaInfo(
            id=97,
            book_id=14,
            chapter_verse_start=(34, 1),
            chapter_verse_end=(40, 0),
            name={MRK_SOURCE: "Йешайа 34–40"},
            url_name="firstsaiah-34-40",
        ),
        ParshaInfo(
            id=98,
            book_id=14,
            chapter_verse_start=(41, 1),
            chapter_verse_end=(44, 0),
            name={MRK_SOURCE: "Йешайа 41–44"},
            url_name="firstsaiah-41-44",
        ),
        ParshaInfo(
            id=99,
            book_id=14,
            chapter_verse_start=(45, 1),
            chapter_verse_end=(49, 0),
            name={MRK_SOURCE: "Йешайа 45–49"},
            url_name="firstsaiah-45-49",
        ),
        ParshaInfo(
            id=100,
            book_id=14,
            chapter_verse_start=(50, 1),
            chapter_verse_end=(58, 0),
            name={MRK_SOURCE: "Йешайа 50–58"},
            url_name="firstsaiah-50-58",
        ),
        ParshaInfo(
            id=101,
            book_id=14,
            chapter_verse_start=(59, 1),
            chapter_verse_end=(66, 0),
            name={MRK_SOURCE: "Йешайа 59–66"},
            url_name="firstsaiah-59-66",
        ),
        ParshaInfo(
            id=102,
            book_id=15,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(6, 0),
            name={MRK_SOURCE: "Ошеа 1–6"},
            url_name="hosea-1-6",
        ),
        ParshaInfo(
            id=103,
            book_id=15,
            chapter_verse_start=(7, 1),
            chapter_verse_end=(12, 0),
            name={MRK_SOURCE: "Ошеа 7–12"},
            url_name="hosea-7-12",
        ),
        ParshaInfo(
            id=104,
            book_id=15,
            chapter_verse_start=(13, 1),
            chapter_verse_end=(14, 0),
            name={MRK_SOURCE: "Ошеа 13–14"},
            url_name="hosea-13-14",
        ),
        ParshaInfo(
            id=105,
            book_id=16,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(4, 0),
            name={MRK_SOURCE: "Йоель 1–4"},
            url_name="joel-1-4",
        ),
        ParshaInfo(
            id=106,
            book_id=17,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(9, 0),
            name={MRK_SOURCE: "Амос 1–9"},
            url_name="amos-1-9",
        ),
        ParshaInfo(
            id=107,
            book_id=18,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(1, 0),
            name={MRK_SOURCE: "Овадья 1–1"},
            url_name="obadiah-1-1",
        ),
        ParshaInfo(
            id=108,
            book_id=19,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(4, 0),
            name={MRK_SOURCE: "Йона 1–4"},
            url_name="jonah-1-4",
        ),
        ParshaInfo(
            id=109,
            book_id=20,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(7, 0),
            name={MRK_SOURCE: "Миха 1–7"},
            url_name="micah-1-7",
        ),
        ParshaInfo(
            id=110,
            book_id=21,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 0),
            name={MRK_SOURCE: "Нахум 1–3"},
            url_name="nahum-1-3",
        ),
        ParshaInfo(
            id=111,
            book_id=22,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 0),
            name={MRK_SOURCE: "Хавакук 1–3"},
            url_name="habakkuk-1-3",
        ),
        ParshaInfo(
            id=112,
            book_id=23,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 0),
            name={MRK_SOURCE: "Цфанья 1–3"},
            url_name="zephaniah-1-3",
        ),
        ParshaInfo(
            id=113,
            book_id=24,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(2, 0),
            name={MRK_SOURCE: "Хагай 1–2"},
            url_name="haggai-1-2",
        ),
        ParshaInfo(
            id=114,
            book_id=25,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(11, 0),
            name={MRK_SOURCE: "Зехарья 1–11"},
            url_name="zechariah-1-11",
        ),
        ParshaInfo(
            id=115,
            book_id=25,
            chapter_verse_start=(12, 1),
            chapter_verse_end=(14, 0),
            name={MRK_SOURCE: "Зехарья 12–14"},
            url_name="zechariah-12-14",
        ),
        ParshaInfo(
            id=116,
            book_id=26,
            chapter_verse_start=(1, 1),
            chapter_verse_end=(3, 0),
            name={MRK_SOURCE: "Малахи 1–3"},
            url_name="malachi-1-3",
        ),
    ],
)
